name: Stale Repo Identifier

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest
    strategy:
      matrix:
        org: ["morganstanley","morganstanley-labs"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Run stale_repos tool
      id: stale-repos
      uses: github/stale-repos@v1
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: ${{ matrix.org }}
        EXEMPT_REPOS: ".github,ospo,morganstanley.github.io,flats,jgss-provider-template"
        EXEMPT_TOPICS: "keep,template"
        INACTIVE_DAYS: 180
        ACTIVITY_METHOD: "pushed"

    - name: Print output of stale_repos tool
      run: echo "${{ steps.stale-repos.outputs.inactiveRepos }}"
    - uses: actions/github-script@v7
      with:
        script: |
          const repos = ${{ steps.stale-repos.outputs.inactiveRepos }}
          for (const repo of repos) {
            console.log(repo);
            const issue = await github.rest.issues.create({
              owner: 'morganstanley',
              repo: 'ospo',
              title: 'Stale repo ' + repo.url,
              body: 'This repo has been stale for ' + repo.daysInactive + ' days. Please contact the owner to make it active again.',
            });
            console.log(issue);
          }
        github-token: ${{ secrets.GH_TOKEN }}
